platform: Any CPU
configuration: Release
shallow_clone: true
version: 6.0.0.{build}
image: Visual Studio 2019

matrix:
  fast_finish: true

# enable AssemblyInfo.cs patching with build version number
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# restore NuGet packages before running MSBuild
before_build:
  - echo CD                             %CD%
  - echo APPVEYOR_PROJECT_NAME          %APPVEYOR_PROJECT_NAME%
  - echo APPVEYOR_PROJECT_SLUG          %APPVEYOR_PROJECT_SLUG%
  - echo APPVEYOR_BUILD_FOLDER          %APPVEYOR_BUILD_FOLDER%
  - echo APPVEYOR_BUILD_ID              %APPVEYOR_BUILD_ID%
  - echo APPVEYOR_BUILD_NUMBER          %APPVEYOR_BUILD_NUMBER%
  - echo APPVEYOR_BUILD_VERSION         %APPVEYOR_BUILD_VERSION%
  - echo APPVEYOR_JOB_ID                %APPVEYOR_JOB_ID%
  - echo APPVEYOR_JOB_NAME              %APPVEYOR_JOB_NAME%
  - echo APPVEYOR_JOB_NUMBER            %APPVEYOR_JOB_NUMBER%
  - echo APPVEYOR_REPO_NAME             %APPVEYOR_REPO_NAME%
  - echo APPVEYOR_REPO_BRANCH           %APPVEYOR_REPO_BRANCH%
  - echo APPVEYOR_REPO_TAG              %APPVEYOR_REPO_TAG%
  - echo APPVEYOR_REPO_TAG_NAME         %APPVEYOR_REPO_TAG_NAME%
  - echo APPVEYOR_REPO_COMMIT           %APPVEYOR_REPO_COMMIT%
  - echo APPVEYOR_REPO_COMMIT_TIMESTAMP %APPVEYOR_REPO_COMMIT_TIMESTAMP%
  - echo NETCORE_MONIKER                %NETCORE_MONIKER%
  - echo FULLFX_MONIKER                 %FULLFX_MONIKER%
  - echo XUNIT_VERSION                  %XUNIT_VERSION%
  - echo OPENCOVER_VERSION              %OPENCOVER_VERSION%
  - dotnet tool install --global coveralls.net --version 1.0.0
  - nuget update -self
  - nuget restore Maestro.sln
  - cinst -y docfx

environment:
  NETCORE_MONIKER: 'netcoreapp3.1'
  FULLFX_MONIKER: 'net471'
  XUNIT_VERSION: '2.4.1'
  OPENCOVER_VERSION: '4.7.922'
  COVERALLS_REPO_TOKEN:
    secure: brg0Fy+w8aO/4JhYrsjvumIqAMCi26QNT3nJGUQNaKvLXSoXgywWn/WPCEnUJEEK

build:
  verbosity: minimal
  parallel: true
  project: Maestro.sln

after_build:
  - set ARTIFACT_RELEASE_LABEL=%APPVEYOR_BUILD_VERSION%
  - appveyor_postbuild.bat

test_script:
- ps: >-
    & ".\Packages\opencover\$($env:OPENCOVER_VERSION)\tools\OpenCover.Console.exe" -filter:"+[OSGeo.*]* -[*.tests]* -[*.Tests]* -[Irony]*" -register:user -target:".\Packages\xunit.runner.console\$($env:XUNIT_VERSION)\tools\$($env:FULLFX_MONIKER)\xunit.console.exe" -targetargs:"OSGeo.MapGuide.MaestroAPI.Tests\bin\Release\$($env:FULLFX_MONIKER)\OSGeo.MapGuide.MaestroAPI.Tests.dll OSGeo.MapGuide.ObjectModels.Tests\bin\Release\$($env:FULLFX_MONIKER)\OSGeo.MapGuide.ObjectModels.Tests.dll -noshadow -xml .\TestResult.xml" -output:OpenCoverCoverage.xml -coverbytest:*.Tests.dll

    & csmacnz.coveralls --opencover -i OpenCoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\TestResult.xml))

artifacts:
  - path: .\artifacts\MapGuideMaestro-$(configuration)-$(ARTIFACT_RELEASE_LABEL)-Setup.exe
    name: installer_windows
  - path: .\artifacts\MapGuideMaestro-$(configuration)-$(ARTIFACT_RELEASE_LABEL).zip
    name: portable_package
  - path: .\artifacts\MgTileSeeder-win-x64-$(ARTIFACT_RELEASE_LABEL).zip
    name: seeder_windows
  - path: .\artifacts\MgTileSeeder-linux-x64-$(ARTIFACT_RELEASE_LABEL).zip
    name: seeder_linux
  - path: .\artifacts\Maestro-MapPublisher-win-x64-$(ARTIFACT_RELEASE_LABEL).zip
    name: publisher_windows
  - path: .\artifacts\Maestro-MapPublisher-linux-x64-$(ARTIFACT_RELEASE_LABEL).zip
    name: publisher_linux
  - path: .\artifacts\*.nupkg
    name: nuget_packages
    type: NuGetPackage

#  - path: .\artifacts\Maestro-SDK-$(ARTIFACT_RELEASE_LABEL).zip
#    name: sdk
#    type: zip

deploy:
  - provider: NuGet
    server:                  # remove to push to NuGet.org
    api_key:
      secure: 74dbOyNChWJyX9bCH+Sb5b7wvsQIgR/OJa0Smt/0tI7/0fxjdxzrhoYmCyS9SlA4
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: 'Release $(appveyor_repo_tag_name) ($(appveyor_build_version))'
    auth_token:
      secure: Dw0UkS+M9jDa7xofORbKLKgTBWZsBTN56QA7xD7F0pCCdNqnLH3K5oFk3smWjRfX
  #  artifact: installer_windows,sdk
    artifact: installer_windows,portable_package,nuget_packages,seeder_windows,seeder_linux
    draft: true
    prerelease: true
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true        # deploy on tag push only